### PR TITLE
Day16

### PR DESCRIPTION
**Pull request by mitoskalandiel**
Done and dusted, lets move on shall we?

---
This change is [Reviewable](https://reviewable.io/reviews/smeierzubiesen/hmh/58)

### CODE REVIEW

**Comment by mitoskalandiel** [comment]
Reviewed 1 of 7 files at r1, 4 of 7 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/smeierzubiesen/hmh/58)*

**Comment by mitoskalandiel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/smeierzubiesen/hmh/58#-:-KmljR8Lf7UKSh1T_r2p:bnfp4nl)*

**Comment by mitoskalandiel** [comment]
yeah still looks good, hope it builds :lgtm: 

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/smeierzubiesen/hmh/58#-:-Kmlnb4Xfr2RAUD1ncsm:bve9lyf)*

**Review by smeierzubiesen — APPROVED** [review]
i know that appveyor fails due to no VS2017 solution being present.
we'll investigate if we can emulate the batch behaviour on appveyor? *I don't see why not*:smzb

**Pull request merged**
